name: Deploy Infrastructure with Terraform
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_environment_variables: true
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  
          
      - name: Terraform Init
        id: init
        run: terraform init
    
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        
      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Extract and Trigger Function
        run: |
          # Get Terraform output and print it for debugging
          echo "Terraform outputs:"
          terraform output
          
          # Save just the value line from the function_url output
          FUNCTION_URL=$(terraform output function_url | grep -v "=" | xargs)
          echo "Extracted Function URL: $FUNCTION_URL"
          
          # Check if it looks like a valid URL
          if [[ $FUNCTION_URL == *"run.app"* ]]; then
            echo "Triggering function at: $FUNCTION_URL"
            curl -v -X POST "$FUNCTION_URL"
          else
            echo "Could not extract valid URL from Terraform output"
            exit 1
          fi

      
    
