name: Deploy Infrastructure with Terraform
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_environment_variables: true
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  
          
      - name: Terraform Init
        id: init
        run: terraform init
    
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        
      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Extract Function URL and Trigger Function
        run: |
          # Extract the URL 
          FUNCTION_URL=$(terraform output -raw function_url | head -n 1)
          echo "Function URL: $FUNCTION_URL"
          
          # Make sure the URL is valid
          if [[ $FUNCTION_URL == https://* ]]; then
            echo "Triggering function at $FUNCTION_URL"
            curl -X POST "$FUNCTION_URL"
          else
            echo "Invalid URL: $FUNCTION_URL"
            echo "Full terraform output:"
            terraform output
            exit 1
          fi
