name: Deploy Infrastructure with Terraform
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_environment_variables: true
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  
          
      - name: Terraform Init
        id: init
        run: terraform init
    
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        
      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Get Function URL
        id: function
        run: |
          # Extract entire terraform output
          TERRAFORM_OUTPUT=$(terraform output)
          # Use grep to extract the URL
          FUNCTION_URL=$(echo "$TERRAFORM_OUTPUT" | grep -o "https://data-ingestion[^\"]*")
          
          if [ -z "$FUNCTION_URL" ]; then
            echo "ERROR: Could not extract function URL"
            echo "$TERRAFORM_OUTPUT"
            exit 1
          fi
          
          echo "Function URL: $FUNCTION_URL"
          echo "url=$FUNCTION_URL" >> $GITHUB_OUTPUT

      - name: Trigger Cloud Run Function
        run: |
          curl -X POST "${{ steps.function.outputs.url }}" \
          -H "Authorization: bearer $(gcloud auth print-identity-token)" \
          -H "Content-Type: application/json" \
          -d '{}'
