name: Deploy Infrastructure with Terraform
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_environment_variables: true
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  
          
      - name: Terraform Init
        id: init
        run: terraform init
    
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        
      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Get Function URL
        run: |
          REGION=${{ secrets.GCP_REGION }}
          PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
          FUNCTION_NAME=${{ secrets.FUNCTION_NAME }}
          
          FUNCTION_URL="https://${REGION}-${PROJECT_ID}.cloudfunctions.net/${FUNCTION_NAME}"
          echo "Function URL: $FUNCTION_URL"
          
          echo "FUNCTION_URL=$FUNCTION_URL" >> $GITHUB_ENV
      
      - name: Trigger Cloud Run Function
        run: |
          curl -X POST "$FUNCTION_URL" \
          -H "Authorization: bearer $(gcloud auth print-identity-token)" \
          -H "Content-Type: application/json" \
          -d '{}'
