name: Deploy Infrastructure with Terraform
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_environment_variables: true
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  
          
      - name: Terraform Init
        id: init
        run: terraform init
    
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        
      - name: Terraform Apply
        run: terraform apply -auto-approve
      - name: Extract and Trigger Function (Simple Approach)
        run: |
          
          terraform output -raw function_url > url.txt
          
          CLEAN_URL=$(head -n 1 url.txt | tr -d '\r\n')
          
          echo "URL from file: $CLEAN_URL"
          
          echo "Waiting 10 seconds for function to be fully available..."
          sleep 10
          
          echo "Triggering function at: $CLEAN_URL"
          curl -X POST "${CLEAN_URL}"
          
